runtime: nodejs20

env_variables:
  PORT: "8080"
  NODE_ENV: "production"

# Cloud SQL connection configuration for App Engine
beta_settings:
  cloud_sql_instances: project-6c0d0bce-1897-4806-852:asia-southeast1:inventory-postgres

