steps:
- name: gcr.io/cloud-builders/npm
  args: ['ci']

# Migration step removed - database table already exists from local setup
# If you need to run migrations in the future, uncomment the migration step below
# or run migrations manually using: node run-migration.js

- name: gcr.io/cloud-builders/gcloud
  args:
    - app
    - deploy
    - --quiet
    - --region=asia-southeast1

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s
