steps:
- name: gcr.io/cloud-builders/npm
  args: ['ci']

- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
      set -e

      # Fetch DATABASE_URL from Secret Manager
      DB_URL="$$(gcloud secrets versions access latest --secret=DATABASE_URL)"

      # Download Cloud SQL Auth Proxy
      curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.11.4/cloud-sql-proxy.linux.amd64
      chmod +x cloud-sql-proxy

      # Start Cloud SQL Proxy
      ./cloud-sql-proxy project-6c0d0bce-1897-4806-852:asia-southeast1:inventory-postgres &
      sleep 10

      # Run database migration
      psql "$$DB_URL" -f migrations/init.sql

- name: gcr.io/cloud-builders/gcloud
  args:
    - app
    - deploy
    - --quiet

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s
